//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// A2.
    /// </summary>
    //  *** Start programmer edit section *** (A2 CustomAttributes)

    //  *** End programmer edit section *** (A2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("A2E", new string[0])]
    [View("A2L", new string[0])]
    public class A2 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (A2 CustomMembers)

        //  *** End programmer edit section *** (A2 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "A2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View A2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("A2E", typeof(IIS.mu1.A2));
                }
            }
            
            /// <summary>
            /// "A2L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View A2L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("A2L", typeof(IIS.mu1.A2));
                }
            }
        }
    }
}
